version: '3.8'

services:
  app:
    container_name: prod-container-flashweb
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: aseem5047/flashweb:prod
    ports:
      - "3000:3000"

    command: npm start